server:
  port: 8088

spring:

  application:
    name: xpayment-adapter-app
  profiles:
    active: kafka
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/iprody-lms

  logging:
    file:
      name: ./logs/application.log
    level:
      root: INFO
      org.hibernate: ERROR
      com.iprody.adapter: INFO
      org.springframework.web: WARN
      org.springframework.data: WARN
      org.springframework.security: WARN
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){green} [%thread] %-5level %logger{36} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
      logback:
        rollingpolicy:
          file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz"
          max-file-size: 500MB
          max-history: 20
          clean-history-on-start: false

  management:
    endpoints:
      web:
        exposure:
          include: health,info,liquibase,beans,metrics,env,loggers
    endpoint:
      health:
        show-details: always