spring:
  application:
    name: payment-service-app
  datasource: # объединяет в себе параметры подключения к БД
    #url: jdbc:postgresql://postgres-db:5432/payment-db # URL подключения к БД
    url: jdbc:postgresql://localhost:5432/payment-db
    username: user # Имя пользователя
    password: secret # Пароль
    driver-class-name: org.postgresql.Driver # класс jdbc драйвера
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # Показывать SQL-запросы в консоли
    properties:
      hibernate:
        format_sql: true # Форматировать SQL для читаемости
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  datasource:
#    username: test
#    password: test
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    database:
#      platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl:
#        auto: update
#
#  h2:
#    console:
#      enabled: true

server:
  port: 8080
