server:
  port: 8082

spring:

  application:
    name: payment-service-app
  profiles:
    active: db,kafka
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/iprody-lms

#  logging:
#    level:
#      root: INFO
#      org.hibernate: ERROR
#      # com.iprody.payment: ERROR
#      org.springframework.web: WARN
#      org.springframework.data: WARN
#      org.springframework.security: WARN

  management:
    endpoints:
      web:
        exposure:
          include: health,info,liquibase,beans,metrics,env,loggers