apiVersion: apps/v1
kind: Deployment
metadata:
  name: xpayment-adapter-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xpayment-adapter-app
  template:
    metadata:
      labels:
        app: xpayment-adapter-app
    spec:
      containers:
        - name: xpayment-adapter-app
          image: xpayment-adapter-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "my-kafka.kafka.svc.cluster.local:9093"
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "xpayment-adapter-result-consumers"
            - name: APP_KAFKA_TOPIC_REQUEST
              value: "xpayment-adapter.requests"
            - name: APP_KAFKA_TOPIC_RESPONSE
              value: "xpayment-adapter.responses"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq.rabbitmq.svc.cluster.local:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: xpayment-adapter-app
spec:
  selector:
    app: xpayment-adapter-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP